# Generated by Django 4.0.5 on 2022-06-17 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nyumba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='phone_number',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='posted_at',
            new_name='post_date',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='authority_center',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='authority_contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='authority_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_center',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', tinymce.models.HTMLField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_post', to='nyumba.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
